# Generated by Django 2.0.7 on 2018-08-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memocard',
            name='theme',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
