# Generated by Django 2.0.7 on 2018-08-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180821_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memocard',
            name='path',
            field=models.CharField(max_length=300),
        ),
    ]
